package input

type InputIDCustomer struct { 
ID int `uri:"id" binding:"required"` 
}

type CustomerInput struct { 
Name string `json:"name"` 
Address string `json:"address"` 
}

//Generated by Micagen at 28 Oktober 2021