package formatter

import "tesss/entity"

type CustomerFormatter struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

func FormatCustomer(customer entity.Customer) CustomerFormatter {
	customerFormatter := CustomerFormatter{}
	customerFormatter.ID = customer.ID
	customerFormatter.Name = customer.Name
	customerFormatter.Address = customer.Address
	return customerFormatter
}
func FormatCustomers(customers []entity.Customer) []CustomerFormatter {
	customersFormatter := []CustomerFormatter{}
	for _, customer := range customers {
		customerFormatter := FormatCustomer(customer)
		customersFormatter = append(customersFormatter, customerFormatter)
	}
	return customersFormatter
}

//Generated by Micagen at 28 Oktober 2021
